; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv32-unknown-elf -mcpu=cl-cypress -mattr=-f -o - %s \
; RUN: 2>&1 | FileCheck %s -check-prefix CHECK -check-prefix CHECK-RV32
; RUN: llc -mtriple riscv32-unknown-elf -mcpu=cl-cypress -mattr=+f,-d -o - %s \
; RUN: 2>&1 | FileCheck %s -check-prefix CHECK -check-prefix CHECK-RV32-F
; RUN: llc -mtriple riscv32-unknown-elf -mcpu=cl-cypress -mattr=+f,+d -o - %s \
; RUN: 2>&1 | FileCheck %s -check-prefix CHECK -check-prefix CHECK-RV32-FD
;
; Checking for special return instructions (sret, mret).
;
define void @foo_machine() #1 {
; CHECK-LABEL: foo_machine:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mret
  ret void
}

;
; Checking all Caller saved registers (arguments and temps)
; and FP registers are all saved when the handler calls another function.
;
; extern int otherfoo();
;
; __attribute__((interrupt)) void foo_s_with_call() {
;   otherfoo();
; }
;

declare i32 @otherfoo(...)
;
; Additionally check frame pointer and return address are properly saved.
;
define void @foo_m_with_call() #1 {
;
; CHECK-RV32-LABEL: foo_m_with_call:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    addi sp, sp, -80
; CHECK-RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw t0, 72(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw t1, 68(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw t2, 64(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a0, 60(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a1, 56(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a2, 52(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a3, 48(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a4, 44(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a5, 40(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a6, 36(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw a7, 32(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw t3, 28(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw t4, 24(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw t5, 20(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw t6, 16(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    csrr t0, mepc
; CHECK-RV32-NEXT:    sw t0, 12(sp)
; CHECK-RV32-NEXT:    csrr t0, mcause
; CHECK-RV32-NEXT:    sw t0, 8(sp)
; CHECK-RV32-NEXT:    csrr t0, mexinfo
; CHECK-RV32-NEXT:    sw t0, 4(sp)
; CHECK-RV32-NEXT:    csrsi mstatus, 8
; CHECK-RV32-NEXT:    call otherfoo
; CHECK-RV32-NEXT:    csrci mstatus, 8
; CHECK-RV32-NEXT:    lw t0, 12(sp)
; CHECK-RV32-NEXT:    csrw mepc, t0
; CHECK-RV32-NEXT:    lw t0, 8(sp)
; CHECK-RV32-NEXT:    csrw mcause, t0
; CHECK-RV32-NEXT:    lw t0, 4(sp)
; CHECK-RV32-NEXT:    csrw mexinfo, t0
; CHECK-RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw t0, 72(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw t1, 68(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw t2, 64(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a0, 60(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a1, 56(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a2, 52(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a3, 48(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a4, 44(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a5, 40(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a6, 36(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw a7, 32(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw t3, 28(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw t4, 24(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw t5, 20(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw t6, 16(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    addi sp, sp, 80
; CHECK-RV32-NEXT:    mret
;
; CHECK-RV32-F-LABEL: foo_m_with_call:
; CHECK-RV32-F:       # %bb.0:
; CHECK-RV32-F-NEXT:    addi sp, sp, -160
; CHECK-RV32-F-NEXT:    sw ra, 156(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw t0, 152(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw t1, 148(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw t2, 144(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a0, 140(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a1, 136(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a2, 132(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a3, 128(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a4, 124(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a5, 120(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a6, 116(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw a7, 112(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw t3, 108(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw t4, 104(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw t5, 100(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    sw t6, 96(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft0, 92(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft1, 88(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft2, 84(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft3, 80(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft4, 76(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft5, 72(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft6, 68(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft7, 64(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa0, 60(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa1, 56(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa2, 52(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa3, 48(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa4, 44(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa5, 40(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa6, 36(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw fa7, 32(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft8, 28(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft9, 24(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft10, 20(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    fsw ft11, 16(sp) # 4-byte Folded Spill
; CHECK-RV32-F-NEXT:    frcsr t0
; CHECK-RV32-F-NEXT:    sw t0, 12(sp)
; CHECK-RV32-F-NEXT:    csrr t0, mepc
; CHECK-RV32-F-NEXT:    sw t0, 8(sp)
; CHECK-RV32-F-NEXT:    csrr t0, mcause
; CHECK-RV32-F-NEXT:    sw t0, 4(sp)
; CHECK-RV32-F-NEXT:    csrr t0, mexinfo
; CHECK-RV32-F-NEXT:    sw t0, 0(sp)
; CHECK-RV32-F-NEXT:    csrsi mstatus, 8
; CHECK-RV32-F-NEXT:    call otherfoo
; CHECK-RV32-F-NEXT:    lw t0, 12(sp)
; CHECK-RV32-F-NEXT:    fscsr t0
; CHECK-RV32-F-NEXT:    csrci mstatus, 8
; CHECK-RV32-F-NEXT:    lw t0, 8(sp)
; CHECK-RV32-F-NEXT:    csrw mepc, t0
; CHECK-RV32-F-NEXT:    lw t0, 4(sp)
; CHECK-RV32-F-NEXT:    csrw mcause, t0
; CHECK-RV32-F-NEXT:    lw t0, 0(sp)
; CHECK-RV32-F-NEXT:    csrw mexinfo, t0
; CHECK-RV32-F-NEXT:    lw ra, 156(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw t0, 152(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw t1, 148(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw t2, 144(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a0, 140(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a1, 136(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a2, 132(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a3, 128(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a4, 124(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a5, 120(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a6, 116(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw a7, 112(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw t3, 108(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw t4, 104(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw t5, 100(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    lw t6, 96(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft0, 92(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft1, 88(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft2, 84(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft3, 80(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft4, 76(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft5, 72(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft6, 68(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft7, 64(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa0, 60(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa1, 56(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa2, 52(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa3, 48(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa4, 44(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa5, 40(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa6, 36(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw fa7, 32(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft8, 28(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft9, 24(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft10, 20(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    flw ft11, 16(sp) # 4-byte Folded Reload
; CHECK-RV32-F-NEXT:    addi sp, sp, 160
; CHECK-RV32-F-NEXT:    mret
;
; CHECK-RV32-FD-LABEL: foo_m_with_call:
; CHECK-RV32-FD:       # %bb.0:
; CHECK-RV32-FD-NEXT:    addi sp, sp, -240
; CHECK-RV32-FD-NEXT:    sw ra, 236(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw t0, 232(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw t1, 228(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw t2, 224(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a0, 220(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a1, 216(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a2, 212(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a3, 208(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a4, 204(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a5, 200(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a6, 196(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw a7, 192(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw t3, 188(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw t4, 184(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw t5, 180(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    sw t6, 176(sp) # 4-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft0, 168(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft1, 160(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft2, 152(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft3, 144(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft4, 136(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft5, 128(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft6, 120(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft7, 112(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa0, 104(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa1, 96(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa2, 88(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa3, 80(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa4, 72(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa5, 64(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa6, 56(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd fa7, 48(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft8, 40(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft9, 32(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft10, 24(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    fsd ft11, 16(sp) # 8-byte Folded Spill
; CHECK-RV32-FD-NEXT:    frcsr t0
; CHECK-RV32-FD-NEXT:    sw t0, 12(sp)
; CHECK-RV32-FD-NEXT:    csrr t0, mepc
; CHECK-RV32-FD-NEXT:    sw t0, 8(sp)
; CHECK-RV32-FD-NEXT:    csrr t0, mcause
; CHECK-RV32-FD-NEXT:    sw t0, 4(sp)
; CHECK-RV32-FD-NEXT:    csrr t0, mexinfo
; CHECK-RV32-FD-NEXT:    sw t0, 0(sp)
; CHECK-RV32-FD-NEXT:    csrsi mstatus, 8
; CHECK-RV32-FD-NEXT:    call otherfoo
; CHECK-RV32-FD-NEXT:    lw t0, 12(sp)
; CHECK-RV32-FD-NEXT:    fscsr t0
; CHECK-RV32-FD-NEXT:    csrci mstatus, 8
; CHECK-RV32-FD-NEXT:    lw t0, 8(sp)
; CHECK-RV32-FD-NEXT:    csrw mepc, t0
; CHECK-RV32-FD-NEXT:    lw t0, 4(sp)
; CHECK-RV32-FD-NEXT:    csrw mcause, t0
; CHECK-RV32-FD-NEXT:    lw t0, 0(sp)
; CHECK-RV32-FD-NEXT:    csrw mexinfo, t0
; CHECK-RV32-FD-NEXT:    lw ra, 236(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw t0, 232(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw t1, 228(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw t2, 224(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a0, 220(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a1, 216(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a2, 212(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a3, 208(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a4, 204(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a5, 200(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a6, 196(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw a7, 192(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw t3, 188(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw t4, 184(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw t5, 180(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    lw t6, 176(sp) # 4-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft0, 168(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft1, 160(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft2, 152(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft3, 144(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft4, 136(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft5, 128(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft6, 120(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft7, 112(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa0, 104(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa1, 96(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa2, 88(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa3, 80(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa4, 72(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa5, 64(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa6, 56(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld fa7, 48(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft8, 40(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft9, 32(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft10, 24(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    fld ft11, 16(sp) # 8-byte Folded Reload
; CHECK-RV32-FD-NEXT:    addi sp, sp, 240
; CHECK-RV32-FD-NEXT:    mret
  %call = call i32 @otherfoo()
  ret void
}

attributes #1 = { nounwind "interrupt"="machine" }
