// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-zbpbo -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV64ZBPBO

// RV64ZBPBO-LABEL: @fsrw(
// RV64ZBPBO-NEXT:  entry:
// RV64ZBPBO-NEXT:    [[RS1_ADDR:%.*]] = alloca i64, align 8
// RV64ZBPBO-NEXT:    [[RS2_ADDR:%.*]] = alloca i64, align 8
// RV64ZBPBO-NEXT:    [[RS3_ADDR:%.*]] = alloca i64, align 8
// RV64ZBPBO-NEXT:    store i64 %rs1, ptr %rs1.addr, align 8
// RV64ZBPBO-NEXT:    store i64 %rs2, ptr %rs2.addr, align 8
// RV64ZBPBO-NEXT:    store i64 %rs3, ptr %rs3.addr, align 8
// RV64ZBPBO-NEXT:    %0 = load i64, ptr %rs1.addr, align 8
// RV64ZBPBO-NEXT:    %conv = trunc i64 %0 to i32
// RV64ZBPBO-NEXT:    %1 = load i64, ptr %rs2.addr, align 8
// RV64ZBPBO-NEXT:    %conv1 = trunc i64 %1 to i32
// RV64ZBPBO-NEXT:    %2 = load i64, ptr %rs3.addr, align 8
// RV64ZBPBO-NEXT:    %conv2 = trunc i64 %2 to i32
// RV64ZBPBO-NEXT:    %3 = call i32 @llvm.riscv.fsr.i32(i32 %conv, i32 %conv1, i32 %conv2)
// RV64ZBPBO-NEXT:    %conv3 = zext i32 %3 to i64
// RV64ZBPBO-NEXT:    ret i64 %conv3
//
long fsrw(long rs1, long rs2, long rs3) {
  return __builtin_riscv_fsr(rs1, rs2, rs3);
}

// RV64ZBPBO-LABEL: @grevi(
// RV64ZBPBO-NEXT:  entry:
// RV64ZBPBO-NEXT:    %rs1.addr = alloca i64, align 8
// RV64ZBPBO-NEXT:    store i64 %rs1, ptr %rs1.addr, align 8
// RV64ZBPBO-NEXT:    %0 = load i64, ptr %rs1.addr, align 8
// RV64ZBPBO-NEXT:    %1 = call i64 @llvm.riscv.rev.i64(i64 %0)
// RV64ZBPBO-NEXT:    ret i64 %1
//
long grevi(long rs1) {
  return __builtin_riscv_rev(rs1);
}
