// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-zbpbo -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV32ZBPBO

// RV32ZBPBO-LABEL: @clz_32_old(
// RV32ZBPBO-NEXT:  entry:
// RV32ZBPBO-NEXT:    %a.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    store i32 %a, ptr %a.addr, align 4
// RV32ZBPBO-NEXT:    %0 = load i32, ptr %a.addr, align 4
// RV32ZBPBO-NEXT:    %1 = call i32 @llvm.ctlz.i32(i32 %0, i1 false)
// RV32ZBPBO-NEXT:    ret i32 %1
//
int clz_32_old(int a) {
  return __builtin_riscv_clz_32(a);
}

// RV32ZBPBO-LABEL: @clz_32_new(
// RV32ZBPBO-NEXT:  entry:
// RV32ZBPBO-NEXT:    %a.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    store i32 %a, ptr %a.addr, align 4
// RV32ZBPBO-NEXT:    %0 = load i32, ptr %a.addr, align 4
// RV32ZBPBO-NEXT:    %1 = call i32 @llvm.ctlz.i32(i32 %0, i1 false)
// RV32ZBPBO-NEXT:    ret i32 %1
//
int clz_32_new(int a) {
  return __builtin_riscv_clz(a);
}

// RV32ZBPBO-LABEL: @fsr(
// RV32ZBPBO-NEXT:  entry:
// RV32ZBPBO-NEXT:    %rs1.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    %rs2.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    %rs3.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    store i32 %rs1, ptr %rs1.addr, align 4
// RV32ZBPBO-NEXT:    store i32 %rs2, ptr %rs2.addr, align 4
// RV32ZBPBO-NEXT:    store i32 %rs3, ptr %rs3.addr, align 4
// RV32ZBPBO-NEXT:    %0 = load i32, ptr %rs1.addr, align 4
// RV32ZBPBO-NEXT:    %1 = load i32, ptr %rs2.addr, align 4
// RV32ZBPBO-NEXT:    %2 = load i32, ptr %rs3.addr, align 4
// RV32ZBPBO-NEXT:    %3 = call i32 @llvm.riscv.fsr.i32(i32 %0, i32 %1, i32 %2)
// RV32ZBPBO-NEXT:    ret i32 %3
//
int fsr(int rs1, int rs2, int rs3) {
  return __builtin_riscv_fsr(rs1, rs2, rs3);
}

// RV32ZBPBO-LABEL: @fsri(
// RV32ZBPBO-NEXT:  entry:
// RV32ZBPBO-NEXT:    %rs1.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    %rs2.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    store i32 %rs1, ptr %rs1.addr, align 4
// RV32ZBPBO-NEXT:    store i32 %rs2, ptr %rs2.addr, align 4
// RV32ZBPBO-NEXT:    %0 = load i32, ptr %rs1.addr, align 4
// RV32ZBPBO-NEXT:    %1 = load i32, ptr %rs2.addr, align 4
// RV32ZBPBO-NEXT:    %2 = call i32 @llvm.riscv.fsr.i32(i32 %0, i32 %1, i32 15)
// RV32ZBPBO-NEXT:    ret i32 %2
//
int fsri(int rs1, int rs2) {
  return __builtin_riscv_fsr(rs1, rs2, 15);
}

// RV32ZBPBO-LABEL: @grevi(
// RV32ZBPBO-NEXT:  entry:
// RV32ZBPBO-NEXT:    %rs1.addr = alloca i32, align 4
// RV32ZBPBO-NEXT:    store i32 %rs1, ptr %rs1.addr, align 4
// RV32ZBPBO-NEXT:    %0 = load i32, ptr %rs1.addr, align 4
// RV32ZBPBO-NEXT:    %1 = call i32 @llvm.riscv.rev.i32(i32 %0)
// RV32ZBPBO-NEXT:    ret i32 %1
//
long grevi(long rs1) {
  return __builtin_riscv_rev(rs1);
}
