// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv32 -O2 -target-feature +experimental-p \
// RUN:   -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-RV32 %s

typedef signed char int8x4_t __attribute((vector_size(4)));
typedef short int16x2_t __attribute((vector_size(4)));
typedef unsigned char uint8x4_t __attribute__((vector_size(4)));
typedef unsigned short uint16x2_t __attribute__((vector_size(4)));

// CHECK-RV32-LABEL: @add8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.add8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @add16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.add16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ave(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ave.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @bitrev(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.bitrev.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @bpick(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.bpick.i32(i32 %a, i32 %b, i32 %c)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @clrs8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.clrs8.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @clrs16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.clrs16.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @clrs32(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.clrs32.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @clz8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.clz8.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @clz16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.clz16.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @clz32(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.clz32.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @cmpeq8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.cmpeq8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @cmpeq16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.cmpeq16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @cras16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.cras16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @crsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.crsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @insb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.insb.i32.i32(i32 %a, i32 %b, i32 3)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kabs8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kabs8.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kabs16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kabs16.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kabsw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kabsw.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kadd8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kadd8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kadd16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kadd16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kaddh(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kaddh.i32.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kaddw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kaddw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kcras16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kcras16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kcrsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kcrsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kdmbb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kdmbb.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kdmbt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kdmbt.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kdmtt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kdmtt.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kdmabb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kdmabb.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kdmabt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kdmabt.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kdmatt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kdmatt.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @khm8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.khm8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @khmx8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.khmx8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @khm16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.khm16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @khmx16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.khmx16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @khmbb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.khmbb.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @khmbt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.khmbt.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @khmtt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.khmtt.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmabb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmabb.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmabt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmabt.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmatt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmatt.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmada(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmada.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmaxda(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmaxda.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmads(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmads.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmadrs(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmadrs.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmaxds(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmaxds.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmda(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmda.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmxda(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmxda.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmac(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmac.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmac_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmac.u.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawb.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawb_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawb.u.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawb2(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawb2.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawb2_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawb2.u.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawt.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawt_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawt.u.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawt2(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawt2.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmawt2_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmawt2.u.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmsb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmsb.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmsb_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmsb.u.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmwb2(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmwb2.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmwb2_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmwb2.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmwt2(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmwt2.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmmwt2_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmmwt2.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmsda(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmsda.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kmsxda(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kmsxda.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ksllw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ksllw.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ksll8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ksll8.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ksll16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ksll16.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kslra8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kslra8.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kslra8_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kslra8.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kslra16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kslra16.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kslra16_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kslra16.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kslraw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kslraw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kslraw_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kslraw.u.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kstas16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kstas16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kstsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kstsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ksub8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ksub8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ksub16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ksub16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ksubh(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ksubh.i32.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ksubw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ksubw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kwmmul(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kwmmul.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @kwmmul_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.kwmmul.u.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @maxw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.maxw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @minw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.minw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @pbsad(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.pbsad.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @pbsada(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.pbsada.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @pkbb16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.pkbb16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @pkbt16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.pkbt16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @pktt16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.pktt16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @pktb16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.pktb16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @radd8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.radd8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @radd16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.radd16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @raddw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.raddw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @rcras16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.rcras16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @rcrsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.rcrsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @rstas16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.rstas16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @rstsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.rstsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @rsub8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.rsub8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @rsub16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.rsub16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @rsubw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.rsubw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sclip8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sclip8.i32.i32(i32 %a, i32 5)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sclip16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sclip16.i32.i32(i32 %a, i32 6)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sclip32(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sclip32.i32.i32(i32 %a, i32 7)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @scmple8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.scmple8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @scmple16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.scmple16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @scmplt8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.scmplt8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @scmplt16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.scmplt16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sll8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sll8.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sll16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sll16.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smaqa(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smaqa.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smaqa_su(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smaqa.su.i32.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smax8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smax8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smax16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smax16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smbb16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smbb16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smbt16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smbt16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smtt16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smtt16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smds(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smds.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smdrs(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smdrs.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smxds(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smxds.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smin8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smin8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smin16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smin16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smmul(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smmul.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smmul_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smmul.u.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smmwb(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smmwb.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smmwb_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smmwb.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smmwt(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smmwt.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @smmwt_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.smmwt.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sra_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sra.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sra8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sra8.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sra8_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sra8.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sra16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sra16.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sra16_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sra16.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @srl8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.srl8.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @srl8_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.srl8.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @srl16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.srl16.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @srl16_u(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.srl16.u.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @stas16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.stas16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @stsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.stsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sub8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sub8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sub16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sub16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sunpkd810(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sunpkd810.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sunpkd820(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sunpkd820.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sunpkd830(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sunpkd830.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sunpkd831(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sunpkd831.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @sunpkd832(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.sunpkd832.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @swap16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.swap16.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uclip8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uclip8.i32.i32(i32 %a, i32 5)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uclip16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uclip16.i32.i32(i32 %a, i32 6)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uclip32(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uclip32.i32.i32.i32(i32 %a, i32 7)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ucmple8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ucmple8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ucmple16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ucmple16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ucmplt8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ucmplt8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ucmplt16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ucmplt16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukadd8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukadd8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukadd16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukadd16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukaddh(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukaddh.i32.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukaddw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukaddw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukcras16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukcras16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukcrsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukcrsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukstas16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukstas16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ukstsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ukstsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uksub8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uksub8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uksub16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uksub16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uksubh(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uksubh.i32.i32.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uksubw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uksubw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @umaqa(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.umaqa.i32(i32 %t, i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @umax8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.umax8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @umax16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.umax16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @umin8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.umin8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @umin16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.umin16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uradd8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uradd8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uradd16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uradd16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @uraddw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.uraddw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @urcras16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.urcras16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @urcrsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.urcrsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @urstas16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.urstas16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @urstsa16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.urstsa16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ursub8(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ursub8.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ursub16(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ursub16.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @ursubw(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.ursubw.i32(i32 %a, i32 %b)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @zunpkd810(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.zunpkd810.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @zunpkd820(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.zunpkd820.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @zunpkd830(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.zunpkd830.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @zunpkd831(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.zunpkd831.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
// CHECK-RV32-LABEL: @zunpkd832(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:      %0 = tail call i32 @llvm.riscv.zunpkd832.i32(i32 %a)
// CHECK-RV32-NEXT:      ret i32 %0
//

unsigned long add8(unsigned long a, unsigned long b) {
  return __builtin_riscv_add8(a, b);
}

unsigned long add16(unsigned long a, unsigned long b) {
  return __builtin_riscv_add16(a, b);
}

long ave(long a, long b) {
  return __builtin_riscv_ave(a, b);
}

unsigned long bitrev(unsigned long a, unsigned long b) {
  return __builtin_riscv_bitrev(a, b);
}

unsigned long bpick(unsigned long a, unsigned long b, unsigned long c) {
  return __builtin_riscv_bpick(a, b, c);
}

unsigned long clrs8(unsigned long a) {
  return __builtin_riscv_clrs8(a);
}

unsigned long clrs16(unsigned long a) {
  return __builtin_riscv_clrs16(a);
}

unsigned long clrs32(unsigned long a) {
  return __builtin_riscv_clrs32(a);
}

unsigned long clz8(unsigned long a) {
  return __builtin_riscv_clz8(a);
}

unsigned long clz16(unsigned long a) {
  return __builtin_riscv_clz16(a);
}

unsigned long clz32(unsigned long a) {
  return __builtin_riscv_clz32(a);
}

unsigned long cmpeq8(unsigned long a, unsigned long b) {
  return __builtin_riscv_cmpeq8(a, b);
}

unsigned long cmpeq16(unsigned long a, unsigned long b) {
  return __builtin_riscv_cmpeq16(a, b);
}

unsigned long cras16(unsigned long a, unsigned long b) {
  return __builtin_riscv_cras16(a, b);
}

unsigned long crsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_crsa16(a, b);
}

unsigned long insb(unsigned long a, unsigned long b) {
  return __builtin_riscv_insb(a, b, 3);
}

unsigned long kabs8(unsigned long a) {
  return __builtin_riscv_kabs8(a);
}

unsigned long kabs16(unsigned long a) {
  return __builtin_riscv_kabs16(a);
}

long kabsw(long a) {
  return __builtin_riscv_kabsw(a);
}

unsigned long kadd8(unsigned long a, unsigned long b) {
  return __builtin_riscv_kadd8(a, b);
}

unsigned long kadd16(unsigned long a, unsigned long b) {
  return __builtin_riscv_kadd16(a, b);
}

long kaddh(int a, int b) {
  return __builtin_riscv_kaddh(a, b);
}

long kaddw(int a, int b) {
  return __builtin_riscv_kaddw(a, b);
}

unsigned long kcras16(unsigned long a, unsigned long b) {
  return __builtin_riscv_kcras16(a, b);
}

unsigned long kcrsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_kcrsa16(a, b);
}

long kdmbb(unsigned int a, unsigned int b) {
  return __builtin_riscv_kdmbb(a, b);
}

long kdmbt(unsigned int a, unsigned int b) {
  return __builtin_riscv_kdmbt(a, b);
}

long kdmtt(unsigned int a, unsigned int b) {
  return __builtin_riscv_kdmtt(a, b);
}

long kdmabb(long t, unsigned int a, unsigned int b) {
  return __builtin_riscv_kdmabb(t, a, b);
}

long kdmabt(long t, unsigned int a, unsigned int b) {
  return __builtin_riscv_kdmabt(t, a, b);
}

long kdmatt(long t, unsigned int a, unsigned int b) {
  return __builtin_riscv_kdmatt(t, a, b);
}

unsigned long khm8(unsigned long a, unsigned long b) {
  return __builtin_riscv_khm8(a, b);
}

unsigned long khmx8(unsigned long a, unsigned long b) {
  return __builtin_riscv_khmx8(a, b);
}

unsigned long khm16(unsigned long a, unsigned long b) {
  return __builtin_riscv_khm16(a, b);
}

unsigned long khmx16(unsigned long a, unsigned long b) {
  return __builtin_riscv_khmx16(a, b);
}

long khmbb(unsigned int a, unsigned int b) {
  return __builtin_riscv_khmbb(a, b);
}

long khmbt(unsigned int a, unsigned int b) {
  return __builtin_riscv_khmbt(a, b);
}

long khmtt(unsigned int a, unsigned int b) {
  return __builtin_riscv_khmtt(a, b);
}

long kmabb(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmabb(t, a, b);
}

long kmabt(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmabt(t, a, b);
}

long kmatt(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmatt(t, a, b);
}

long kmada(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmada(t, a, b);
}

long kmaxda(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmaxda(t, a, b);
}

long kmads(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmads(t, a, b);
}

long kmadrs(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmadrs(t, a, b);
}

long kmaxds(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmaxds(t, a, b);
}

long kmda(unsigned long a, unsigned long b) {
  return __builtin_riscv_kmda(a, b);
}

long kmxda(unsigned long a, unsigned long b) {
  return __builtin_riscv_kmxda(a, b);
}

long kmmac(long t, long a, long b) {
  return __builtin_riscv_kmmac(t, a, b);
}

long kmmac_u(long t, long a, long b) {
  return __builtin_riscv_kmmac_u(t, a, b);
}

long kmmawb(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawb(t, a, b);
}

long kmmawb_u(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawb_u(t, a, b);
}

long kmmawb2(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawb2(t, a, b);
}

long kmmawb2_u(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawb2_u(t, a, b);
}

long kmmawt(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawt(t, a, b);
}

long kmmawt_u(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawt_u(t, a, b);
}

long kmmawt2(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawt2(t, a, b);
}

long kmmawt2_u(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmmawt2_u(t, a, b);
}

long kmmsb(long t, long a, long b) {
  return __builtin_riscv_kmmsb(t, a, b);
}

long kmmsb_u(long t, long a, long b) {
  return __builtin_riscv_kmmsb_u(t, a, b);
}

long kmmwb2(long a, unsigned long b) {
  return __builtin_riscv_kmmwb2(a, b);
}

long kmmwb2_u(long a, unsigned long b) {
  return __builtin_riscv_kmmwb2_u(a, b);
}

long kmmwt2(long a, unsigned long b) {
  return __builtin_riscv_kmmwt2(a, b);
}

long kmmwt2_u(long a, unsigned long b) {
  return __builtin_riscv_kmmwt2_u(a, b);
}

long kmsda(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmsda(t, a, b);
}

long kmsxda(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_kmsxda(t, a, b);
}

long ksllw(long a, unsigned int b) {
  return __builtin_riscv_ksllw(a, b);
}

unsigned long ksll8(unsigned long a, unsigned int b) {
  return __builtin_riscv_ksll8(a, b);
}

unsigned long ksll16(unsigned long a, unsigned int b) {
  return __builtin_riscv_ksll16(a, b);
}

unsigned long kslra8(unsigned long a, int b) {
  return __builtin_riscv_kslra8(a, b);
}

unsigned long kslra8_u(unsigned long a, int b) {
  return __builtin_riscv_kslra8_u(a, b);
}

unsigned long kslra16(unsigned long a, int b) {
  return __builtin_riscv_kslra16(a, b);
}

unsigned long kslra16_u(unsigned long a, int b) {
  return __builtin_riscv_kslra16(a, b);
}

unsigned long kslraw(int a, int b) {
  return __builtin_riscv_kslraw(a, b);
}

unsigned long kslraw_u(int a, int b) {
  return __builtin_riscv_kslraw_u(a, b);
}

unsigned long kstas16(unsigned long a, unsigned long b) {
  return __builtin_riscv_kstas16(a, b);
}

unsigned long kstsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_kstsa16(a, b);
}

unsigned long ksub8(unsigned long a, unsigned long b) {
  return __builtin_riscv_ksub8(a, b);
}

unsigned long ksub16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ksub16(a, b);
}

long ksubh(int a, int b) {
  return __builtin_riscv_ksubh(a, b);
}

long ksubw(int a, int b) {
  return __builtin_riscv_ksubw(a, b);
}

long kwmmul(long a, long b) {
  return __builtin_riscv_kwmmul(a, b);
}

long kwmmul_u(long a, long b) {
  return __builtin_riscv_kwmmul_u(a, b);
}

long maxw(int a, int b) {
  return __builtin_riscv_maxw(a, b);
}

long minw(int a, int b) {
  return __builtin_riscv_minw(a, b);
}

unsigned long pbsad(unsigned long a, unsigned long b) {
  return __builtin_riscv_pbsad(a, b);
}

unsigned long pbsada(unsigned long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_pbsada(t, a, b);
}

unsigned long pkbb16(unsigned long a, unsigned long b) {
  return __builtin_riscv_pkbb16(a, b);
}

unsigned long pkbt16(unsigned long a, unsigned long b) {
  return __builtin_riscv_pkbt16(a, b);
}

unsigned long pktt16(unsigned long a, unsigned long b) {
  return __builtin_riscv_pktt16(a, b);
}

unsigned long pktb16(unsigned long a, unsigned long b) {
  return __builtin_riscv_pktb16(a, b);
}

unsigned long radd8(unsigned a, unsigned b) {
  return __builtin_riscv_radd8(a, b);
}

unsigned long radd16(unsigned long a, unsigned long b) {
  return __builtin_riscv_radd16(a, b);
}

long raddw(int a, int b) {
  return __builtin_riscv_raddw(a, b);
}

unsigned long rcras16(unsigned long a, unsigned long b) {
  return __builtin_riscv_rcras16(a, b);
}

unsigned long rcrsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_rcrsa16(a, b);
}

unsigned long rstas16(unsigned long a, unsigned long b) {
  return __builtin_riscv_rstas16(a, b);
}

unsigned long rstsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_rstsa16(a, b);
}

unsigned long rsub8(unsigned long a, unsigned long b) {
  return __builtin_riscv_rsub8(a, b);
}

unsigned long rsub16(unsigned long a, unsigned long b) {
  return __builtin_riscv_rsub16(a, b);
}

long rsubw(int a, int b) {
  return __builtin_riscv_rsubw(a, b);
}

unsigned long sclip8(unsigned long a) {
  return __builtin_riscv_sclip8(a, 5);
}

unsigned long sclip16(unsigned long a) {
  return __builtin_riscv_sclip16(a, 6);
}

long sclip32(long a) {
  return __builtin_riscv_sclip32(a, 7);
}

unsigned long scmple8(unsigned long a, unsigned long b) {
  return __builtin_riscv_scmple8(a, b);
}

unsigned long scmple16(unsigned long a, unsigned long b) {
  return __builtin_riscv_scmple16(a, b);
}

unsigned long scmplt8(unsigned long a, unsigned long b) {
  return __builtin_riscv_scmplt8(a, b);
}

unsigned long scmplt16(unsigned long a, unsigned long b) {
  return __builtin_riscv_scmplt16(a, b);
}

unsigned long sll8(unsigned long a, unsigned int b) {
  return __builtin_riscv_sll8(a, b);
}

unsigned long sll16(unsigned long a, unsigned int b) {
  return __builtin_riscv_sll16(a, b);
}

long smaqa(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_smaqa(t, a, b);
}

long smaqa_su(long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_smaqa_su(t, a, b);
}

unsigned long smax8(unsigned long a, unsigned long b) {
  return __builtin_riscv_smax8(a, b);
}

unsigned long smax16(unsigned long a, unsigned long b) {
  return __builtin_riscv_smax16(a, b);
}

long smbb16(unsigned long a, unsigned long b) {
  return __builtin_riscv_smbb16(a, b);
}

long smbt16(unsigned long a, unsigned long b) {
  return __builtin_riscv_smbt16(a, b);
}

long smtt16(unsigned long a, unsigned long b) {
  return __builtin_riscv_smtt16(a, b);
}

long smds(unsigned long a, unsigned long b) {
  return __builtin_riscv_smds(a, b);
}

long smdrs(unsigned long a, unsigned long b) {
  return __builtin_riscv_smdrs(a, b);
}

long smxds(unsigned long a, unsigned long b) {
  return __builtin_riscv_smxds(a, b);
}

unsigned long smin8(unsigned long a, unsigned long b) {
  return __builtin_riscv_smin8(a, b);
}

unsigned long smin16(unsigned long a, unsigned long b) {
  return __builtin_riscv_smin16(a, b);
}

long smmul(long a, long b) {
  return __builtin_riscv_smmul(a, b);
}

long smmul_u(long a, long b) {
  return __builtin_riscv_smmul_u(a, b);
}

long smmwb(long a, unsigned long b) {
  return __builtin_riscv_smmwb(a, b);
}

long smmwb_u(long a, unsigned long b) {
  return __builtin_riscv_smmwb_u(a, b);
}

long smmwt(long a, unsigned long b) {
  return __builtin_riscv_smmwt(a, b);
}

long smmwt_u(long a, unsigned long b) {
  return __builtin_riscv_smmwt_u(a, b);
}

long sra_u(long a, unsigned int b) {
  return __builtin_riscv_sra_u(a, b);
}

unsigned long sra8(unsigned long a, unsigned int b) {
  return __builtin_riscv_sra8(a, b);
}

unsigned long sra8_u(unsigned long a, unsigned int b) {
  return __builtin_riscv_sra8_u(a, b);
}

unsigned long sra16(unsigned long a, unsigned int b) {
  return __builtin_riscv_sra16(a, b);
}

unsigned long sra16_u(unsigned long a, unsigned int b) {
  return __builtin_riscv_sra16_u(a, b);
}

unsigned long srl8(unsigned long a, unsigned int b) {
  return __builtin_riscv_srl8(a, b);
}

unsigned long srl8_u(unsigned long a, unsigned int b) {
  return __builtin_riscv_srl8_u(a, b);
}

unsigned long srl16(unsigned long a, unsigned int b) {
  return __builtin_riscv_srl16(a, b);
}

unsigned long srl16_u(unsigned long a, unsigned int b) {
  return __builtin_riscv_srl16_u(a, b);
}

unsigned long stas16(unsigned long a, unsigned long b) {
  return __builtin_riscv_stas16(a, b);
}

unsigned long stsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_stsa16(a, b);
}

unsigned long sub8(unsigned long a, unsigned long b) {
  return __builtin_riscv_sub8(a, b);
}

unsigned long sub16(unsigned long a, unsigned long b) {
  return __builtin_riscv_sub16(a, b);
}

unsigned long sunpkd810(unsigned long a) {
  return __builtin_riscv_sunpkd810(a);
}

unsigned long sunpkd820(unsigned long a) {
  return __builtin_riscv_sunpkd820(a);
}

unsigned long sunpkd830(unsigned long a) {
  return __builtin_riscv_sunpkd830(a);
}

unsigned long sunpkd831(unsigned long a) {
  return __builtin_riscv_sunpkd831(a);
}

unsigned long sunpkd832(unsigned long a) {
  return __builtin_riscv_sunpkd832(a);
}

unsigned long swap16(unsigned long a) {
  return __builtin_riscv_swap16(a);
}

unsigned long uclip8(unsigned long a) {
  return __builtin_riscv_uclip8(a, 5);
}

unsigned long uclip16(unsigned long a) {
  return __builtin_riscv_uclip16(a, 6);
}

long uclip32(long a) {
  return __builtin_riscv_uclip32(a, 7);
}

unsigned long ucmple8(unsigned long a, unsigned long b) {
  return __builtin_riscv_ucmple8(a, b);
}

unsigned long ucmple16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ucmple16(a, b);
}

unsigned long ucmplt8(unsigned long a, unsigned long b) {
  return __builtin_riscv_ucmplt8(a, b);
}

unsigned long ucmplt16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ucmplt16(a, b);
}

unsigned long ukadd8(unsigned long a, unsigned long b) {
  return __builtin_riscv_ukadd8(a, b);
}

unsigned long ukadd16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ukadd16(a, b);
}

long ukaddh(int a, int b) {
  return __builtin_riscv_ukaddh(a, b);
}

long ukaddw(int a, int b) {
  return __builtin_riscv_ukaddw(a, b);
}

unsigned long ukcras16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ukcras16(a, b);
}

unsigned long ukcrsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ukcrsa16(a, b);
}

unsigned long ukstas16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ukstas16(a, b);
}

unsigned long ukstsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ukstsa16(a, b);
}

unsigned long uksub8(unsigned long a, unsigned long b) {
  return __builtin_riscv_uksub8(a, b);
}

unsigned long uksub16(unsigned long a, unsigned long b) {
  return __builtin_riscv_uksub16(a, b);
}

unsigned long uksubh(unsigned int a, unsigned int b) {
  return __builtin_riscv_uksubh(a, b);
}

unsigned long uksubw(unsigned int a, unsigned int b) {
  return __builtin_riscv_uksubw(a, b);
}

unsigned long umaqa(unsigned long t, unsigned long a, unsigned long b) {
  return __builtin_riscv_umaqa(t, a, b);
}

unsigned long umax8(unsigned long a, unsigned long b) {
  return __builtin_riscv_umax8(a, b);
}

unsigned long umax16(unsigned long a, unsigned long b) {
  return __builtin_riscv_umax16(a, b);
}

unsigned long umin8(unsigned long a, unsigned long b) {
  return __builtin_riscv_umin8(a, b);
}

unsigned long umin16(unsigned long a, unsigned long b) {
  return __builtin_riscv_umin16(a, b);
}

unsigned long uradd8(unsigned long a, unsigned long b) {
  return __builtin_riscv_uradd8(a, b);
}

unsigned long uradd16(unsigned long a, unsigned long b) {
  return __builtin_riscv_uradd16(a, b);
}

unsigned long uraddw(unsigned int a, unsigned int b) {
  return __builtin_riscv_uraddw(a, b);
}

unsigned long urcras16(unsigned long a, unsigned long b) {
  return __builtin_riscv_urcras16(a, b);
}

unsigned long urcrsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_urcrsa16(a, b);
}

unsigned long urstas16(unsigned long a, unsigned long b) {
  return __builtin_riscv_urstas16(a, b);
}

unsigned long urstsa16(unsigned long a, unsigned long b) {
  return __builtin_riscv_urstsa16(a, b);
}

unsigned long ursub8(unsigned long a, unsigned long b) {
  return __builtin_riscv_ursub8(a, b);
}

unsigned long ursub16(unsigned long a, unsigned long b) {
  return __builtin_riscv_ursub16(a, b);
}

unsigned long ursubw(unsigned int a, unsigned int b) {
  return __builtin_riscv_ursubw(a, b);
}

unsigned long zunpkd810(unsigned long a) {
  return __builtin_riscv_zunpkd810(a);
}

unsigned long zunpkd820(unsigned long a) {
  return __builtin_riscv_zunpkd820(a);
}

unsigned long zunpkd830(unsigned long a) {
  return __builtin_riscv_zunpkd830(a);
}

unsigned long zunpkd831(unsigned long a) {
  return __builtin_riscv_zunpkd831(a);
}

unsigned long zunpkd832(unsigned long a) {
  return __builtin_riscv_zunpkd832(a);
}
